field: 4a958693-7fff-4370-9cb0-f29094b9a59a # Blog Content
fieldLayouts:
  897a6142-883d-4c23-a1f4-e8c5dd959a96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 954afdc9-9207-4fa5-9909-6ad99c7bf738 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92a0fe56-bb23-42ae-be08-abe8ad1e66e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3ff4fe4-82c2-43b6-a825-296557d46d0e # Image Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ae956f9-dd8f-43c5-a953-32276e2cbc29
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f062d44-b4cd-489d-b11d-a007f2ba9f13
        userCondition: null
fields:
  954afdc9-9207-4fa5-9909-6ad99c7bf738: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:7105bdf9-b659-4be7-86fb-82b5842a9aac' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:7105bdf9-b659-4be7-86fb-82b5842a9aac' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:7105bdf9-b659-4be7-86fb-82b5842a9aac' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a3ff4fe4-82c2-43b6-a825-296557d46d0e: # Image Type
    columnSuffix: sszlvcck
    contentColumnType: string
    fieldGroup: null
    handle: imageType
    instructions: null
    name: 'Image Type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Normal
            -
              - value
              - normal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - fullWidth
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Info Graphic'
            -
              - value
              - infoGraphic
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 1
