field: 4a958693-7fff-4370-9cb0-f29094b9a59a # Blog Content
fieldLayouts:
  48c5fd72-b144-465f-b7d5-c27d6b7eee73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7d22a631-a00b-48c7-8749-78b1d56ba997 # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: beb4c2e9-0529-4326-9990-11d64c17ba79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3ba62f6-c044-44de-b585-046b4f24f903 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0bb7b00-289f-4b12-9767-ad3d1a3283b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: af22c048-367f-414e-a903-023df60682a6
        userCondition: null
fields:
  7d22a631-a00b-48c7-8749-78b1d56ba997: # Quote
    columnSuffix: ehgdolbf
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3ba62f6-c044-44de-b585-046b4f24f903: # Heading
    columnSuffix: jofidptc
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 3
