field: 4a958693-7fff-4370-9cb0-f29094b9a59a # Blog Content
fieldLayouts:
  964f7cb1-126b-444e-9dbe-8fd563e0916f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b346d35a-bfd0-489d-a4e4-d32d51c88a5f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97ea5543-3cd4-4fcf-b923-ed559f9c2a93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96b8ae46-c320-449e-bdf1-4bb729ce9716 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ea77c19-5c83-474d-9e5a-8aac986ef1a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3dccdf22-ac09-40aa-a0ba-37a6768df750
        userCondition: null
fields:
  96b8ae46-c320-449e-bdf1-4bb729ce9716: # Heading
    columnSuffix: wvlkkwfx
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b346d35a-bfd0-489d-a4e4-d32d51c88a5f: # Text
    columnSuffix: frjibqgd
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 66072694-b792-4b64-aff3-32d4454130ec # Full
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: text
name: Text
sortOrder: 2
