headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
options:
  alignment:
    options:
      - left
      - right
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - '|'
  - sourceEditing
  - code
  - style
  - heading
  - insertImage
  - '|'
  - bold
  - italic
  - link
  - alignment
  - '|'
  - underline
  - strikethrough
  - subscript
  - superscript
  - fontSize
  - fontFamily
  - fontColor
  - mediaEmbed
  - fontBackgroundColor
  - htmlEmbed
  - blockQuote
  - insertTable
  - codeBlock
  - bulletedList
  - numberedList
  - todoList
  - outdent
  - indent
  - horizontalLine
  - pageBreak
  - selectAll
  - findAndReplace
  - undo
  - redo
  - '|'
