columnSuffix: sgcvixvy
contentColumnType: text
fieldGroup: 8d062821-eba9-49af-a1e0-6a7592a2e63f # Globals
handle: alertTitle
instructions: null
name: 'Alert Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
