columnSuffix: eigpugic
contentColumnType: text
fieldGroup: 99db65d5-c28d-46fc-8730-4bca558848f1 # Common
handle: pageContent
instructions: null
name: 'Page Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 66072694-b792-4b64-aff3-32d4454130ec # Full
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
