defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  030d2dcd-d5bc-4228-8924-3ab95c77d733: # JayGreentree
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
